class Prompts:
    @staticmethod
    def generate_draft(instructions: str, context: str) -> str:
        return f"Context: {context}\n\nInstructions: {instructions}\n\nWrite a creative draft based on the above."

    @staticmethod
    def analyze_content(content: str) -> str:
        return f"Analyze the following text and extract new characters (entities) and key plot updates. Return JSON with keys 'new_entities' (list) and 'updates' (list).\n\nText: {content}"

    @staticmethod
    def generate_timeline(content: str, character_profiles: str = "") -> str:
        char_instruction = ""
        if character_profiles:
            char_instruction = (
                "\n### Character Visual Consistency:\n"
                "Use the following character definitions to ensure consistent descriptions in 'visual_prompt'. "
                "Whenever a character appears, explicitly describe their key visual features (e.g. hair, clothes) based on these profiles:\n"
                f"{character_profiles}\n"
            )

        return (
            "You are a professional film storyboard artist. "
            "Break down the following story text into a sequence of storyboard shots based on 'Independent Action Units'.\n"
            "\n"
            "### Principles:\n"
            "1. **Action Unit Division**: Each shot must correspond to ONE complete and independent action. Do NOT merge multiple distinct actions into one shot.\n"
            "2. **Visual Variety**: Use diverse shot types and camera movements to enhance storytelling rhythm.\n"
            f"{char_instruction}"
            "\n"
            "### Required Output Format (JSON Object):\n"
            "Return a JSON object with a key 'shots' containing a list of shot objects. Example:\n"
            "{\n"
            "  \"shots\": [\n"
            "    {\n"
            "      \"id\": 1,\n"
            "      \"shot_type\": \"Medium Shot\",\n"
            "      \"camera_movement\": \"Static\",\n"
            "      \"camera_angle\": \"Eye-level\",\n"
            "      \"visual_prompt\": \"Detailed English description of scene visuals, subject, environment, lighting\",\n"
            "      \"audio_prompt\": \"Background music and sound effects in English\",\n"
            "      \"dialogue\": \"Speaker: Line\",\n"
            "      \"duration\": 4.0\n"
            "    }\n"
            "  ]\n"
            "}\n\n"
            f"Story Text:\n{content}"
        )

    @staticmethod
    def extract_character_profiles(content: str) -> str:
        return (
            "Analyze the story text and extract a list of characters. "
            "For each character, provide:\n"
            "- 'name': Name\n"
            "- 'role': 'main', 'supporting', or 'minor'\n"
            "- 'description': Brief biography and personality\n"
            "- 'visual_tags': A dictionary of visual traits for AI image generation. "
            "MUST include keys: 'hair', 'eyes', 'skin_tone', 'face_features', 'build', 'clothing', 'accessories' (e.g. glasses, jewelry). "
            "Make descriptions specific (e.g. 'scar on left cheek', 'round wire-rimmed glasses').\n"
            "\n"
            "Return the result as a JSON object with a key 'profiles' containing the list of character objects.\n\n"
            f"Text: {content}"
        )

    @staticmethod
    def analyze_character_evolution(character_json: str, new_text: str) -> str:
        return (
            "You are a Character Consistency Manager for a long-running series. "
            "Compare the existing character data with their appearance in the NEW CHAPTER TEXT.\n"
            "\n"
            f"### Existing Character Data:\n{character_json}\n"
            "\n"
            f"### New Chapter Text:\n{new_text}\n"
            "\n"
            "### Task:\n"
            "Determine if the character's appearance in the new text requires a new 'Variant' (e.g. new outfit, new hairstyle) "
            "or if it's just a temporary state (e.g. wet, dirty, injured) or no change.\n"
            "\n"
            "### Output JSON:\n"
            "{\n"
            "  \"action\": \"new_variant\" | \"keep_current\" | \"scene_modifier\",\n"
            "  \"reason\": \"Explanation of why...\",\n"
            "  \"new_variant\": { \"name\": \"...\", \"tags\": \"...\" } (Only if action is 'new_variant'),\n"
            "  \"modifier_tags\": \"...\" (Only if action is 'scene_modifier', keywords for prompt)\n"
            "}"
        )

    @staticmethod
    def generate_cinematic_grid_timeline_prompt(content: str, character_profiles: str = "") -> str:
        char_instruction = ""
        if character_profiles:
            char_instruction = (
                "\n### Character Visual Consistency:\n"
                "Use the following character definitions to ensure consistent descriptions in 'visual_prompt'. "
                "Whenever a character appears, explicitly describe their key visual features (e.g. hair, clothes) based on these profiles:\n"
                f"{character_profiles}\n"
            )

        return (
            "You are a professional film storyboard artist. "
            "Break down the following story text into a 'Cinematic Grid' sequence of exactly 9 shots. "
            "This structure ensures perfect coverage for video production.\n"
            "\n"
            "### The 9-Shot Grid Structure (Mandatory):\n"
            "1. **Extreme Long Shot (ELS)**: Establishing context, vast environment.\n"
            "2. **Long Shot (LS)**: Full body subject, standing naturally.\n"
            "3. **Medium Long Shot (MLS)**: Knees up, showing stance/posture.\n"
            "4. **Medium Shot (MS)**: Waist up, key action/attitude.\n"
            "5. **Medium Close-Up (MCU)**: Chest up, emotion/interaction.\n"
            "6. **Close-Up (CU)**: Face tight, emotional clarity.\n"
            "7. **Extreme Close-Up (ECU)**: Macro detail (eye, hand, object).\n"
            "8. **Low Angle Shot**: Looking up (heroic/imposing).\n"
            "9. **High Angle Shot**: Looking down (vulnerability/overview).\n"
            "\n"
            f"{char_instruction}"
            "\n"
            "### Required Output Fields (JSON Object):\n"
            "Return a JSON object with a key 'shots' containing a list of exactly 9 objects (one for each shot type above) with the following fields:\n"
            "- 'id': sequential number (1-9)\n"
            "- 'shot_type': The specific type from the list above (ELS, LS, MLS, MS, MCU, CU, ECU, Low Angle, High Angle)\n"
            "- 'camera_movement': Choose one [Static, Pan, Tilt, Zoom In, Zoom Out, Tracking, Handheld] appropriate for the shot.\n"
            "- 'camera_angle': Must match the shot type implication (e.g., Low Angle for Shot 8, High for Shot 9, others as appropriate).\n"
            "- 'visual_prompt': A highly detailed English description for image generation. "
            "Structure: [Subject/Action] + [Environment/Context] + [Lighting/Atmosphere] + [Art Style/Tech Specs]. MUST be in ENGLISH.\n"
            "- 'audio_prompt': Description of background music (BGM) and sound effects (SFX). MUST be in ENGLISH.\n"
            "- 'dialogue': 'Speaker: Line' or null. IF the input story text is in Chinese, this field MUST be in Chinese. If English, keep English.\n"
            "- 'duration': Estimated duration in seconds.\n"
            "\n"
            f"Story Text:\n{content}"
        )
    @staticmethod
    def generate_storyboard_grid_prompt(story_text: str) -> str:
        return (
            "STORY-TO-STORYBOARD META-PROMPT\n"
            "\n"
            "IMPORTANT: Do not create the image, create the detailed prompt for the image.\n"
            "\n"
            "The image prompt must make reference to the story and reference image provided by user, the prompt must follow exactly the details of the image prompt\n"
            "\n"
            "When the user provides a short story synopsis, follow these steps:\n"
            "\n"
            "Analyze the synopsis and identify:\n"
            "- The main subject(s) (person, pair, group, creature, vehicle, object)\n"
            "- Their appearance and defining traits\n"
            "- The environment and tone\n"
            "- The emotional or narrative beat\n"
            "- Lighting/mood implied by the story\n"
            "\n"
            "Create a full 3×3 cinematic storyboard grid with 9 distinct shots of the same subject(s) in the same environment, using consistent wardrobe, lighting, and atmosphere.\n"
            "\n"
            "Output a single cohesive AI image prompt that includes all 9 frames (labeled 1–9), using the following structure:\n"
            "\n"
            "OUTPUT FORMAT\n"
            "\n"
            "Cinematic 3×3 Storyboard Prompt\n"
            "\n"
            "Story Synopsis (interpreted):\n"
            "<one-sentence interpretation of the user’s synopsis>\n"
            "\n"
            "Create a professional 3×3 cinematic storyboard grid featuring the same subject(s) from the synopsis in the same environment.\n"
            "Maintain total consistency in appearance, clothing, lighting, mood, and environmental details.\n"
            "Each panel represents a distinct camera shot following cinematic conventions.\n"
            "\n"
            "Row 1 — Establishing Context\n"
            "Extreme Long Shot (ELS):\n"
            "Full environment revealed, subject(s) small in frame. Match the story’s setting, lighting, and mood.\n"
            "\n"
            "Long Shot (LS):\n"
            "Entire subject(s) visible head-to-toe (or full object/vehicle), standing naturally within the environment.\n"
            "\n"
            "Medium Long Shot (MLS / 3-4 / American Shot):\n"
            "Subject(s) framed from knees up (or 3/4 angle for objects), showing stance, posture, and core emotion.\n"
            "\n"
            "Row 2 — Core Coverage\n"
            "Medium Shot (MS):\n"
            "Waist-up framing. Capture the key action, attitude, or emotional beat implied by the story.\n"
            "\n"
            "Medium Close-Up (MCU):\n"
            "Chest-up. Focus on emotion, expression, micro-interaction, or narrative tension.\n"
            "\n"
            "Close-Up (CU):\n"
            "Tight shot of the face (or front detail of an object). Cinematic depth of field, emotional clarity.\n"
            "\n"
            "Row 3 — Details & Angles\n"
            "Extreme Close-Up (ECU):\n"
            "Macro detail: eyes, hands, symbolic object, texture, or a key story element.\n"
            "\n"
            "Low Angle Shot (Worm’s Eye):\n"
            "Camera looking up at the subject(s) from below. Dramatic, heroic, or imposing based on the story’s tone.\n"
            "\n"
            "High Angle Shot (Bird’s Eye):\n"
            "Camera looking down from above. Spatial clarity, vulnerability, or overview of action.\n"
            "\n"
            "Global Requirements\n"
            "- Same subject from image prompt(s) in all 9 frames\n"
            "- Same clothing, hairstyle, props, weapons, or accessories\n"
            "- Same lighting conditions and color grading\n"
            "- Consistent environment and weather\n"
            "- Correct realism and cinematic depth of field per shot\n"
            "- Photorealistic textures\n"
            "- Cinematic camera behavior and focal-length accuracy\n"
            "\n"
            "Final Line (technical):\n"
            "Extract the still x.y\n"
            "(Where x.y refers to the grid coordinate or still number the user later requests.)\n"
            "\n"
            f"Input Story:\n{story_text}"
        )
