"""add_scene_model

Revision ID: 34f39772067e
Revises: e98517defbec
Create Date: 2026-01-29 13:53:26.579317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f39772067e'
down_revision: Union[str, None] = 'e98517defbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('audio_prompt', sa.Text(), nullable=True),
    sa.Column('dialogue', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('asset_status', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('asset_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_id'), 'scene', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_id'), table_name='scene')
    op.drop_table('scene')
    # ### end Alembic commands ###
