"""add_camera_fields

Revision ID: b9e2bb22e2bb
Revises: 34f39772067e
Create Date: 2026-01-29 16:27:33.241126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e2bb22e2bb'
down_revision: Union[str, None] = '34f39772067e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('shot_type', sa.String(length=50), nullable=True))
    op.add_column('scene', sa.Column('camera_movement', sa.String(length=50), nullable=True))
    op.add_column('scene', sa.Column('camera_angle', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'camera_angle')
    op.drop_column('scene', 'camera_movement')
    op.drop_column('scene', 'shot_type')
    # ### end Alembic commands ###
