"""add_user_id_to_project

Revision ID: c1a2b3c4d5e6
Revises: b9e2bb22e2bb
Create Date: 2026-01-31 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a2b3c4d5e6'
down_revision: Union[str, None] = 'b9e2bb22e2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###
